export const unitTypes = {
    NONE: 'null',
    SQUARE_METERS: 'SquareMeters',
    RUB_PER_MONTH: 'RubPerMonth',
    KILOWATT: 'Kilowatts',
    CUBE_METERS_PER_HOUR: 'CubicMetersPerHour',
    FLOORS: 'Floors',
    SQUARE_METERS_PER_YEAR: 'SquareMetersPerYear',
    RUB: 'Rubles',
    PERCENTS: 'Percents',
    PER_YEAR: 'PerYear',
    TON_PER_SQUARE_METER: 'TonPerSquareMeters',
    CELCIUS: 'Celcius',
    RUB_PER_SQUARE_METERS_PER_YEAR: 'RubPerSquareMetersPerYear',
    RUB_PER_SQUARE_METERS_PER_MONTH: 'RubPerSquareMetersPerMonth',
    RUB_PER_YEAR: 'RubPerYear',
    PALLET_PLACE: 'PalletPlace',
    PIECES: 'Pieces',
    METERS: 'Meters',
    TON: 'Tons'
};
